
server.port: 8000
#Resiliencej configurations
resilience4j:
  circuitbreaker:
    config:
      default:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 6s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED
    instances:
      productServiceBreaker:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 6s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED



#spring configs
spring:
  main:
    web-application-type: reactive
  application:
    name: api-gateway
  cloud:
    gateway:
      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders:
            - "Origin"
            - "Content-Type"
            - "Accept"
            - "Authorization"
            - "Referer"
            allowedMethods:
            - POST
            - GET
            - OPTION
      routes:
      - id: health-service
        uri: lb://health-service  # Load-balanced route to Service Two
        predicates:
        - Path=/health/**
        filters:
        - name: InMemoryRateLimiter
          args:
            keyResolver: "#{@apiKeyResolver}"
            limit: 5
            httpStatus: 429
        - name: CircuitBreaker
          args:
            name: health-service
            fallbackUri: forward:/healthservice/fallback

apiKeyResolver:
  name: apiKeyResolver
  class: org.springframework.cloud.gateway.filter.ratelimit.KeyResolver
  uriKeyExtractor: "#{'defaultKey'}"
  userKeyExtractor: "#{'defaultKey'}"

inMemoryRateLimiter:
  name: inMemoryRateLimiter
  class: com.demo.apigateway.config.InMemoryRateLimiterGatewayFilterFactory$Config
  keyResolver: "#{@apiKeyResolver}"
  limit: 5
  httpStatus: 429  # You can customize the HTTP status code


#client-secret: qmHnZe1IYvSedAlO1G9ykgPBozBptAyx
