
server.port: 8000
#Resiliencej configurations
resilience4j:
  circuitbreaker:
    config:
      default:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 6s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED
    instances:
      productServiceBreaker:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 6s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED



#spring configs
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
      - id: health-service
        uri: lb://health-service  # Load-balanced route to Service Two
        predicates:
        - Path=/health/**
        filters:
        - name: CircuitBreaker
          args:
            name: health-service
            fallbackUri: forward:/healthservice/fallback
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: 'http://localhost:4200'
            allowedHeaders:
              - Content-Type
## routes end


#client-secret: qmHnZe1IYvSedAlO1G9ykgPBozBptAyx